sudo: required
solution: PoC.SharpDiff.sln
language: csharp
dotnet: 3.0.100
mono: none
jdk: openjdk10

install:
  - sudo apt-get install -qq dotnet-sdk-2.0.0

script:
  - git fetch --unshallow || true
  - bash ./tools/travis-build.sh
  
